### ISSUE TITLE
Sound Effect Folders Override DAT Files

### ISSUE THREAD

**Issue by MainMemory** [sonicretro/sadx-mod-loader#11]
If you have a mod with a sound effect folder, mods loaded after it with a matching DAT file should override the folder, but do not.

**Comment by MainMemory** [comment]
Potential solutions: hardcode the filemap to set sound effect folder's index file to replace the dat, or add a map associating each replaced file with the index of the mod that contains the replacement file.

**Comment by GerbilSoft** [comment]
I'd recommend doing something like this instead to avoid having two maps with duplicated strings:

```
struct {
    std::string filename;
    int modIdx;
} fileInfo;
std::unordered_map<std::string, fileInfo> m_fileMap;
```

(I used a struct instead of std::pair<> because that makes it easier to figure out what's what instead of having a million "first" and "second" entries everywhere.)
