### ISSUE TITLE
DLL Error: The Specified Module Cannot Be Found

### ISSUE THREAD

**Issue by supercoolsonic** [sonicretro/sadx-mod-loader#20]
I recently released a mod of mine here:
https://github.com/supercoolsonic/SADXDC-SET-Layout-Fixes/issues/7
However, multiple people are reporting that the title of this issue is what greets them when they try to run it. It was compiled in Visual Studio 2013. Dude recompiled it in Visual Studio 2015, and some of the level geometry was invisible. I'm not sure what's causing this. The DLL file is in the mod folder, and the name of the DLL in the INI file is correct.

**Comment by MainMemory** [comment]
They probably don't have the MSVC 2013 x86 redist installed.
The invisible geometry issue is weird though, just changing compilers shouldn't do that.

**Comment by supercoolsonic** [comment]
I'll ask them to try it and see what happens. Thanks for the advice.

**Comment by supercoolsonic** [comment]
Out of curiosity, have you tried it yourself? Does it work for you? The one from the download link I provided near the bottom of that topic, I mean.

**Comment by MainMemory** [comment]
Oh. MSVCR120D.DLL. That's a debug library, you need to upload a Release build when you want other people to use it, or they'll have to have Visual Studio 2013 installed.

**Comment by supercoolsonic** [comment]
Ohhh. How do I do that?

**Comment by supercoolsonic** [comment]
Never mind. I got it.

**Comment by MainMemory** [comment]
If you had mentioned the actual DLL in the message from the start, I would have been able to identify the actual problem immediately, instead of guessing.

Also, this thread has absolutely nothing to do with SADX Mod Loader. If you have an issue with a mod, you should probably try to contact myself or SonicFreak94 directly, on Twitter, or IRC, or a private message somewhere.

**Comment by supercoolsonic** [comment]
Sorry. I'll close it. Thanks for helping, though.
