### ISSUE TITLE
Model imports crashes randomly

### ISSUE THREAD

**Issue by Benji23245** [sonicretro/sadx-mod-loader#22]
It appears on the latest version of the mod loader, some models import work, and some crash and I have not the slightest clue about this.

Importing something like a cube or a triangle face work, but importing Sonic Generations's Super Sonic head crash. Importing SA2 Super Sonic head on the other hand seem to work, but importing a piece of the Generation Super head containing less polys than the SA2 head still crash, so it's not related to the high poly count.

**Comment by MainMemory** [comment]
I forget, did we sort this out in IRC?

**Comment by Benji23245** [comment]
Well not really, I think I did something like redownload SATOOLS or something.

**Comment by sewer56lol** [comment]
Unrelated but sounds like the start of a conversation that will probably end on IRC.
I'm taking a small break but see you there :3

**Comment by MainMemory** [comment]
Well either way, sounds like the issue has been resolved. Closing.
