### ISSUE TITLE
Mod download throws an error message for GitHub-hosted mods

### ISSUE THREAD

**Issue by PiKeyAr** [sonicretro/sadx-mod-loader#24]
![image](https://user-images.githubusercontent.com/23312549/33802236-c18e6546-ddb5-11e7-944a-af8ef55dab10.png)
![image](https://user-images.githubusercontent.com/23312549/33802261-5cc9c6ea-ddb6-11e7-8b6f-b8ed93b30c84.png)

After one of the recent Mod Loader updates, the above error appears when attempting to repair or force update any mod that is hosted on GitHub. If the file mentioned in the error is deleted, the Mod Manager redownloads it and throws the same error.

**Comment by PiKeyAr** [comment]
Tested in the latest update, it works now but a command prompt window shows up briefly while the mod is being installed, which wasn't the case previously.

**Comment by MainMemory** [comment]
It was never programmed to hide the window, so the fact it didn't show up before is pure happenstance. I should probably tell it to hide the window though.
