### ISSUE TITLE
UI suggestion: shift+click an arrow button to move the mod(s) to the top/bottom of the mod list

### ISSUE THREAD

**Issue by PiKeyAr** [sonicretro/sadx-mod-loader#25]
This would help organize large mod lists much easier, for example this will save a lot of extra clicks with mods like SADXFE, which are recommended to be loaded first, but are moved towards the bottom by default.

**Comment by MainMemory** [comment]
We could also add separate "move to top" and "move to bottom" buttons, instead of requiring you to hold a key.
