### ISSUE TITLE
Custom window titles not displaying with the "Windowed Fullscreen" option enabled

### ISSUE THREAD

**Issue by PiKeyAr** [sonicretro/sadx-mod-loader#26]
Yeah I know, I'm probably the only person using this feature, but still. If the game is run in windowed mode when "Windowed Fullscreen" is enabled in the Mod Manager, the game's window title doesn't change to the title specified by mod.ini's WindowTitle setting.

If this isn't fixable, I suggest removing the feature entirely since nobody has really used it for a long time, and I ended up disabling it anyway because stuff like Fusion's Chao Editor checks the for the original SADXPC window title, so people were complaining that it isn't compatible.

**Comment by MainMemory** [comment]
Whoops, forgot to mention the issue in the commit. Fixed.
