### ISSUE TITLE
Add a warning to the "Codes" tab

### ISSUE THREAD

**Issue by PiKeyAr** [sonicretro/sadx-mod-loader#30]
It seems to be a recurrent problem that people go to the "Codes" tab and just enable everything without being aware of the consequences.

Examples:
1) Many people enable the Super Sonic flag because they think it is required for the Super Sonic mod to work, or attempt to use it thinking it would provide the same functionality as the Super Sonic mod.
2) I haven't confirmed this myself, but apparently "All characters unlocked in Adventure mode" and/or "Tails can play Emerald Coast" can interfere with certain story flags, which leads to a corrupt save file, and the player is unable to complete the story (e.g. Knuckles' story before Chaos 2 fight) unless they replay the whole game on a new save without codes.

A warning message informing the user about potential consequences of using codes could be helpful. A simple warning that the feature is mainly for mod developers would also suffice.

**Comment by MainMemory** [comment]
The "Super Sonic flag" code should just be removed, it serves no practical purpose. Unlocking all the characters should have no effect on story progression, and the Tails code could possibly be worked around. The codes are intended for general use, not specifically for mod developers.

**Comment by cheatfreak47** [comment]
I actually agree that a warning should be added with a "do not show this again" checkbox on it when opening the codes tab of this and all the mod loaders actually, but especially with SADX.

The warning should probably be something like:

**About Codes:**
Some codes may cause undesirable results, such as save data corruption or problems that may not be obvious at first glance. For this reason, it's is recommended that you backup your _saved games_ before using codes with your game. If you believe you have encountered an issue with a mod and you use a code in this codes menu, it is recommended you verify that the issue you are experiencing isn't related to a code you are using or have previously used before reporting it to the developer.

I think that you would also be nice to make it so there's a button that opens this games saved game folder so the user can back up their saves first.

**Comment by MainMemory** [comment]
Codes shouldn't be causing crashes or save data corruption though.

**Comment by cheatfreak47** [comment]
Well, I can guarantee some of the "Unlock all" type codes can break story flags and cause the game to stop progressing the story in some places, I haven't reproduced it myself, but i have seen a lot of reports from people complaining about the game story getting stuck, and as soon as I ask it comes out that they used some sort of code.

**Comment by PiKeyAr** [comment]
I renamed the "Tails Can Play Emerald Coast" code to let the potential user know it can break the save file.
