### ISSUE TITLE
Make option menu in configs wider.

### ISSUE THREAD

**Issue by SurDno** [sonicretro/sadx-mod-loader#35]
I guess it would be better to replace that little arrow in a corner with a wide column, so even pressing on text will lead to option menu, something like this:
![example](https://user-images.githubusercontent.com/35204405/35625611-03e3c30c-06a4-11e8-9f7f-28aca2635fdf.png)

**Comment by MainMemory** [comment]
The control's behavior cannot be configured in that way. You can double-click on the category text to expand/shrink it though.
