### ISSUE TITLE
"Force Mipmapping" option makes Chao controls hard to read

### ISSUE THREAD

**Issue by EternityEngine** [sonicretro/sadx-mod-loader#36]
When I have "Force Mipmapping" enabled, the labels on the controls in the Chao Garden become grey and hard to read. Disabling it rectifies the issue.

Mipmapping on:

![sadx mipmaps](https://user-images.githubusercontent.com/20052973/36456272-ed1ffb12-1658-11e8-995f-0cbf0583d0de.png)

Mipmapping off:

![sadx mipmaps2](https://user-images.githubusercontent.com/20052973/36456278-f5096084-1658-11e8-8589-9b97d4c95bf2.png)

**Comment by MainMemory** [comment]
That's a known issue.

**Comment by EternityEngine** [comment]
Oh, whoops. I imagine you're referring to #28 ? When I searched for mipmapping in the issues the only one that came up was #5 .
