### ISSUE TITLE
Minor Mod Manager UI layout issues

### ISSUE THREAD

**Issue by PiKeyAr** [sonicretro/sadx-mod-loader#38]
On a clean Windows 7 install the Mod Manager looks like this:
![image](https://user-images.githubusercontent.com/23312549/37553615-fb89b534-2a0e-11e8-9db2-7e1b3a6ca54f.png)
The "move to top" and "move to bottom" arrows don't display properly. This wasn't a problem on Windows 8.1, so I imagine it has to do with the fonts installed by default/externally.
All symbols from [this page](https://unicode-table.com/en/sets/arrows-symbols/) appear fine on a clean install, and it has stuff like ↥ and ↧ that you might consider as a replacement for top/bottom arrows.

**Comment by PiKeyAr** [comment]
It also looks like the buttons have incorrect size at 100% DPI on Windows 7:
![image](https://user-images.githubusercontent.com/23312549/38865005-85c3aa90-4277-11e8-9995-35529cf22373.png)

**Comment by GerbilSoft** [comment]
Should be closed with PR #43.

**Comment by PiKeyAr** [comment]
I've tried on both 7 and 10 with 100% and 125% DPI and it look great. The UI also appears more spacious now, which makes it much easier to look at.

There are a few other minor things I caught, such as this (Win7, 125% DPI)
![image](https://user-images.githubusercontent.com/23312549/39689818-02a35678-5213-11e8-8fb0-a430db7965e6.png)
And this, which has been there ever since the update system was introduced:
![image](https://user-images.githubusercontent.com/23312549/39689844-18175bda-5213-11e8-9845-398b4ecf0fe3.png)
Other than those (and perhaps #40), the UI of the Mod Manager looks great at both 100% and 125% DPI now.

**Comment by GerbilSoft** [comment]
The WinForms layout managers need to be reworked to handle this, but I haven't been able to figure it out properly. (Qt's layout managers are significantly easier to work with.)

**Comment by MainMemory** [comment]
I don't like how it makes the mod manager incongruous with the rest of the system.
