### ISSUE TITLE
Mod Manager options concept

### ISSUE THREAD

**Issue by PiKeyAr** [sonicretro/sadx-mod-loader#40]
Here's a concept I made for SADX Mod Manager's Graphics tab that gets rid of the separate Config button:
![image](https://user-images.githubusercontent.com/23312549/39414171-8b203dc6-4c6f-11e8-9adc-9a6ce8319781.png)
A couple of notes/suggestions:
1) Framerate settings could be more specific, i.e. 60 FPS instead of "High". There's a tooltip that helps, but I think it would be better if it said 60 FPS straight away.
2) The framerate/fog/clip level section is called "Graphics" here, which is the same as the name of the tab, I think the tab could just be renamed to "Video".
3) The spacing between sections isn't consistent in the above mockup, but it can still be used as a reference for general item layout.

**Comment by RinMaru** [comment]
I vote cheatfreak simply because its all bunched together in a nice way

**Comment by PiKeyAr** [comment]
If the Input Mod is ever integrated into the Mod Loader, some kind of an interface to make SDL controller maps would be nice, especially if it has a controller picture like the SDL Gamepad Tool and other game config programs.

That said, I'm not a big fan of clustering everything together. The above mockup looks too busy and I'm sure it will be confusing to new users. It looks nothing like SADX's default autorun program or other config tools. The "Display" section has at least three categories of options: display related (resolution, vsync, scaling), window size related and things like detail level and fog settings, which have nothing to do with the previous two categories. Also, unless the window size of the Mod Manager is somehow a major concern, making it more spacious will be a bit easier on the eyes. I'd even go further and hide a lot of these with an "Advanced options" checkbox (not a button that opens a separate window), because who changes fog settings anyway? Some kind of an "optimal" profile would also be nice, like if you press it the Mod Loader sets the screen's native resolution, fullscreen mode and maximum detail level.

**Comment by cheatfreak47** [comment]
I actually agree with PkR, his is a lot better laid out, I just figured I'd try something that doesn't change the size of the window back when I decided to make that

**Comment by PiKeyAr** [comment]
![image](https://user-images.githubusercontent.com/23312549/85149976-ea0b5c00-b28c-11ea-80cc-c7b4d21a312a.png)
While a little different from the concept, I think it works well enough for me to close this.
