### ISSUE TITLE
Some text I typed

### ISSUE THREAD

**Issue by fancymelonub** [sonicretro/sadx-mod-loader#48]
Wish there was a "Discussion" tab for projects, oh well.
Anyways, it has been a while since I'd played any modern Sonic game, I guess I can use this and maybe SA2B as stepping stones.

**Comment by fancymelonub** [comment]
_Welp, I knew that was gonna happen._

**Comment by MainMemory** [comment]
If you need a venue for discussion related to the mod loader, try our [IRC channel](irc://irc.badnik.zone/x-hax) ([webchat](http://chat.mibbit.com/?server=irc.badnik.zone&channel=%23x-hax)) or [Discord](https://discord.gg/wsNdZ4d). If you just want to talk about Sonic games, try a Sonic fan site.

**Comment by fancymelonub** [comment]
There's a Discord for SADX Modding? Cool.
