### ISSUE TITLE
Manually configuring a mod?

### ISSUE THREAD

**Issue by JerryWester** [sonicretro/sadx-mod-loader#63]
This is more of a question than an issue. The menu works almost perfectly running under Wine with Mono except that the config menu for mods only displays a blank screen. Is it possible to manually write a config.ini?

**Comment by PiKeyAr** [comment]
The file configschema.xml in the mod folder contains groups and properties that the mod expects to see in config.ini. Using that as a reference it's possible to write config.ini manually.
```
[Group name]
Property name=Value
```

**Comment by JerryWester** [comment]
Awesome, thank you so much!
