### ISSUE TITLE
Resizable window: black models in chao areas

### ISSUE THREAD

**Issue by kellsnc** [sonicretro/sadx-mod-loader#80]
In all chao areas except the main gardens, most (chunk?) models turn black when the window is resized. 
Leaving the area entirely restores the textures. It happens with vanilla settings.

![blackmodels](https://user-images.githubusercontent.com/32032763/116461353-6f29af00-a868-11eb-84df-70ecb5e0a0df.jpg)

**Comment by kellsnc** [comment]
It also happens when you resize the window while fishing with Big, although the texture fix themselves after a few seconds.

<img width="960" alt="2021-05-03" src="https://user-images.githubusercontent.com/32032763/116894476-5e938300-ac32-11eb-8f26-2da60db7445d.png">

**Comment by PiKeyAr** [comment]
I think it may be related to the light type not being reset correctly. I checked what writes to the current light type value, and it was two instructions, one at `00412409` and another at `0041243B`. When Big's lure is underwater, the instruction at `0041243B` no longer executes. Same thing in most Chao areas except the gardens.
It looks like the following check doesn't work:
```
if ( type_level / 2 != lig_curGjPaletteNo___ )
  {
    lig_curGjPaletteNo___ = type_level / 2;
    dsSetPalette(type_level / 2);
  }
  ```
My guess is, either the light type setting function at `412420` isn't being called in these areas, or the light type is set to some strange value that causes errors resetting it.

**Comment by michael-fadely** [comment]
https://github.com/sonicretro/sadx-mod-loader/blob/2e27d01ec7d77ea9caf1b509ddae3c73c61be120/SADXModLoader/direct3d.cpp#L268

Wouldn't it make more sense to just pass in `CurrentLightType * 2` (which I guess would also be `lig_curGjPaletteNo___ * 2`) (the lighting function divides its input by 2)? Especially since the function is not getting called anymore, it's important to make sure the last requested light type is the one to get set.

**Comment by michael-fadely** [comment]
> Even better: use the proper D3D interfaces to store all the lighting info before a reset, and then restore it after a reset.

I will make a PR with this implemented.

**Comment by kellsnc** [comment]
I assumed that 0 was the default lighting and that, in situations where the game doesn't set any lighting itself (which is why it goes black) it would need the default anyway.

But yeah what you said sounds better!
